# Generated by Django 2.2.2 on 2019-06-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_diary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Blog',
        ),
    ]
