# Generated by Django 2.2.2 on 2019-06-28 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190628_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
